### ISSUE TITLE
C3W1_Assignment.ipynb: wrong remove_stopwords implementation

### ISSUE THREAD

**Issue by eavelardev** [https-deeplearning-ai/tensorflow-1-public#71]
The notebook mention you should get a vocabulary that contains 29714 words, but that vocab still contains stop words. That's because a basic implementation of `remove_stopwords` just removes the stop words without consider that ones with punctuation as a part of the word. So if there is a word in a sentence like `about.` (`about` being a stop word) when `fit_on_texts` is implemented, `about` will be part of the vocab. 
With an implementation using `re` I got a vocab of 29608 words
```python
for word in stopwords:
    sentence = re.sub(rf'\b{word}\b', '', sentence)
```
Another approach is using a `TextVectorization` layer. With the next standardize method I got the same number of words, 29608 + 1(`''`).

```python
def custom_standardization(input_data):
    
    text = tf.strings.lower(input_data)
    text = tf.strings.regex_replace(text, '[%s]' % re.escape(string.punctuation), ' ')

    for word in stopwords:
        text = tf.strings.regex_replace(text, rf'\b{word}\b', '')

    return text
```

**Comment by andres-zartab** [comment]
Thanks for your suggestion. For this particular exercise it is fine that learners submit this function without accounting for words with punctuation since regexp hasn't been covered but we will consider this for future iterations. 

We have updated this notebook recently to let learners know that they need to only consider whitespace as the separation mechanism between words.
